# Generated by Django 4.2.7 on 2025-01-22 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procura', models.BooleanField(default=False)),
                ('plan_percentage', models.CharField(max_length=10)),
                ('real_percentage', models.CharField(max_length=10)),
                ('deviation_percentage', models.CharField(max_length=10)),
                ('phase', models.CharField(choices=[('Factibilizacion', 'Factibilizacion'), ('Planificacion', 'Planificacion'), ('Ejecucion', 'Ejecucion')], default='Factibilizacion', max_length=15)),
                ('status', models.CharField(choices=[('Activo', 'Activo'), ('Reprogramado', 'Reprogramado'), ('Replanificado', 'Replanificado'), ('Pausado', 'Pausado'), ('En cierre', 'En cierre'), ('Culminado', 'Culminado'), ('Cancelado', 'Cancelado')], default='Activo', max_length=15)),
                ('estatus', models.CharField(choices=[('Por iniciar', 'Por iniciar'), ('P.E.C', 'P.E.C'), ('Adelantado', 'Adelantado'), ('A tiempo', 'A tiempo'), ('En alerta', 'En alerta'), ('En riesgo', 'En riesgo'), ('Suspendido', 'Suspendido'), ('Cerrado', 'Cerrado'), ('Cancelado', 'Cancelado')], default='Por iniciar', max_length=15)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
