# Generated by Django 4.2.7 on 2025-01-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='deviation_percentage',
            new_name='planned_percentage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='plan_percentage',
        ),
        migrations.AddField(
            model_name='project',
            name='deviation',
            field=models.CharField(blank=True, default='0%', max_length=10),
        ),
    ]
