# Generated by Django 6.1.1 on 2026-09-28 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0003_rename_deviation_percentage_project_planned_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('month_number', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField(default=2024)),
                ('in_progress', models.PositiveIntegerField(default=0, verbose_name='En Curso')),
                ('paused', models.PositiveIntegerField(default=0, verbose_name='Pausado')),
                ('closing', models.PositiveIntegerField(default=0, verbose_name='En Cierre (PAP OK)')),
                ('completed', models.PositiveIntegerField(default=0, verbose_name='Culminados')),
                ('cancelled', models.PositiveIntegerField(default=0, verbose_name='Cancelado')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Tendencia Mensual',
                'verbose_name_plural': 'Tendencias Mensuales',
                'ordering': ['year', 'month_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['first_name', 'last_name', 'username'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar_color',
            field=models.CharField(default='#FF5733', max_length=20, verbose_name='Color de Avatar'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='Intentos Fallidos de Inicio de Sesión'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Personal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='poo',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='POO / Cargo'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Coordinador', 'Coordinador'), ('PMO', 'PMO'), ('Invitado', 'Invitado')], default='Coordinador', max_length=25, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID / Código de Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='cut_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Corte'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Culminación'),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, default='', verbose_name='Objetivo del Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deviation',
            field=models.CharField(blank=True, default='0%', max_length=10, verbose_name='% Desviación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estatus',
            field=models.CharField(choices=[('Plan en Construcción', 'Plan en Construcción'), ('Por iniciar', 'Por iniciar'), ('Adelantado', 'Adelantado'), ('A tiempo', 'A tiempo'), ('En alerta', 'En alerta'), ('En riesgo', 'En riesgo'), ('Suspendido', 'Suspendido'), ('Sin plan', 'Sin plan'), ('Sin indicador', 'Sin indicador'), ('Cerrado', 'Cerrado'), ('Cancelado', 'Cancelado')], db_index=True, default='Por iniciar', max_length=30, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Líder / Propietario'),
        ),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('Factibilizacion', 'Factibilización'), ('Planificacion', 'Planificación'), ('Ejecucion', 'Ejecución')], db_index=True, default='Factibilizacion', max_length=25, verbose_name='Fase'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_percentage',
            field=models.CharField(default='0%', max_length=10, verbose_name='% Plan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='procura',
            field=models.BooleanField(default=False, verbose_name='Procura'),
        ),
        migrations.AlterField(
            model_name='project',
            name='real_percentage',
            field=models.CharField(default='0%', max_length=10, verbose_name='% Real'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Re-planificado', 'Re-planificado'), ('Reprogramado', 'Reprogramado'), ('Pausado', 'Pausado'), ('Cancelado', 'Cancelado'), ('En cierre', 'En cierre'), ('Culminado', 'Culminado'), ('PAP OK', 'PAP OK')], db_index=True, default='Activo', max_length=25, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Entregable')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('phase', models.CharField(choices=[('Factibilizacion', 'Factibilización'), ('Planificacion', 'Planificación'), ('Ejecucion', 'Ejecución')], default='Factibilizacion', max_length=25, verbose_name='Fase')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='% Avance')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='admin_user.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Entregable',
                'verbose_name_plural': 'Entregables',
                'ordering': ['due_date', 'id'],
            },
        ),
    ]
